"""
Virtual Oscilloscope class that mimics the Keysight DSOX3024a interface for testing and simulation purposes.
This module provides a software simulation of an oscilloscope for development and testing without physical hardware.
"""

from __future__ import annotations

import inspect
import math
from numbers import Real
from types import MappingProxyType
from typing import Any, Callable, Mapping, Optional, Sequence, Tuple, Union

import numpy as np
import pandas as pd

from .oscilloscope import Oscilloscope
from ..virtual_instrument import (
    VirtualInstrument,
    warn_for_large_simulation_points,
)


class VirtualScope(VirtualInstrument, Oscilloscope):
    """
    Virtual version of the KeysightDSOX3024a oscilloscope for simulation/testing.
    Stores state internally and generates synthetic data.

    Supports per-instance hook injection (`waveform_hook`, `channel_hook`, `data_hook`)
    with strict precedence over the deprecated shared `sample` (ferroelectric) fallback.

    Attributes:
        channel (list): Available channels [1-4]
        vdiv (tuple): Vertical division range (min, max) in volts
        y_range (tuple): Vertical range (min, max) in divisions
        y_position (tuple): Vertical position range (min, max)
        input_coupling (list): Available coupling modes ["AC", "DC"]
        probe_attenuation (tuple): Probe attenuation range (min, max)
        tdiv (tuple): Time division range (min, max) in seconds
        x_range (tuple): Horizontal range (min, max) in seconds
        x_position (tuple): Horizontal position range (min, max)
        trigger_source (list): Available trigger sources
        trigger_level (tuple): Trigger level range (min, max) in volts
        trigger_slope (list): Available trigger slope modes
        trigger_mode (list): Available trigger modes
        trigger_sweep (list): Available trigger sweep modes
        acquisition_mode (list): Available acquisition modes
        acquisition_points (tuple): Number of points range (min, max)
    """

    channel = [1, 2, 3, 4]
    vdiv = (0.001, 5.0)
    y_range = (0.008, 40.0)
    y_position = (-40.0, 40.0)
    input_coupling = ["AC", "DC"]
    probe_attenuation = (0.001, 10000.0)
    tdiv = (0.000000002, 50.0)
    x_range = (0.00000002, 500.0)
    x_position = (-500.0, 500.0)
    trigger_source = [1, 2, 3, 4, "EXT", "LINE", "WGEN"]
    trigger_level = (-6.0, 6.0)
    trigger_slope = ["POS", "NEG", "EITH", "ALT"]
    trigger_mode = ["EDGE"]
    trigger_sweep = ["AUTO", "NORM"]
    acquisition_mode = ["NORM", "AVER", "HRES", "PEAK"]
    acquisition_points = (100, 1000)

    _DECLARED_UNITS: Mapping[str, str] = MappingProxyType({
        "voltage": "V",
        "time": "s",
    })

    def __init__(
        self,
        address: str = "VIRTUAL",
        waveform_hook: Optional[Callable[..., Any]] = None,
        channel_hook: Optional[Callable[..., Any]] = None,
        data_hook: Optional[Callable[..., Any]] = None,
        simulation_points: Optional[int] = None,
        **kwargs: Any,
    ) -> None:
        """
        Initialize virtual oscilloscope with default settings.

        Args:
            address: Virtual address for the instrument (default: 'VIRTUAL').
            waveform_hook: Per-instance hook callable returning waveform data (times, voltages).
            channel_hook: Alias for waveform_hook.
            data_hook: Alias for waveform_hook.
            simulation_points: Maximum number of samples generated by synthetic acquisition.
            **kwargs: Additional arguments passed to parent classes.
        """
        super().__init__(address=address, simulation_points=simulation_points, **kwargs)

        hooks = [h for h in (waveform_hook, channel_hook, data_hook) if h is not None]
        if len(hooks) > 1 and any(h is not hooks[0] for h in hooks[1:]):
            raise ValueError("Cannot specify multiple conflicting hook callables")

        hook = hooks[0] if hooks else None

        self.state: dict[str, Any] = {
            "channels_on": {ch: True for ch in self.channel},
            "vdiv": {ch: 1.0 for ch in self.channel},
            "y_range": {ch: 8.0 for ch in self.channel},
            "y_position": {ch: 0.0 for ch in self.channel},
            "input_coupling": {ch: "DC" for ch in self.channel},
            "probe_attenuation": {ch: 1.0 for ch in self.channel},
            "tdiv": 1e-3,
            "x_range": 8e-3,
            "x_position": 0.0,
            "trigger_source": "CHAN1",
            "trigger_level": 0.0,
            "trigger_slope": "POS",
            "trigger_mode": "EDGE",
            "trigger_sweep": "AUTO",
            "acquisition_mode": "NORM",
            "acquisition_channel": 1,
            "running": False,
            "armed": False,
        }
        self._requested_acquisition_points: Optional[int] = None

        self._waveform_hook: Optional[Callable[..., Any]] = None
        self.set_waveform_hook(hook)

    @property
    def declared_units(self) -> Mapping[str, str]:
        """Declared physical units for virtual oscilloscope quantities."""
        return self._DECLARED_UNITS

    @property
    def waveform_hook(self) -> Optional[Callable[..., Any]]:
        """Return the injected per-instance waveform hook."""
        return self._waveform_hook

    @waveform_hook.setter
    def waveform_hook(self, hook: Optional[Callable[..., Any]]) -> None:
        self.set_waveform_hook(hook)

    @property
    def channel_hook(self) -> Optional[Callable[..., Any]]:
        """Return the injected per-instance waveform hook (alias)."""
        return self._waveform_hook

    @channel_hook.setter
    def channel_hook(self, hook: Optional[Callable[..., Any]]) -> None:
        self.set_waveform_hook(hook)

    @property
    def data_hook(self) -> Optional[Callable[..., Any]]:
        """Return the injected per-instance waveform hook (alias)."""
        return self._waveform_hook

    @data_hook.setter
    def data_hook(self, hook: Optional[Callable[..., Any]]) -> None:
        self.set_waveform_hook(hook)

    def set_waveform_hook(self, hook: Optional[Callable[..., Any]]) -> None:
        """
        Inject a per-instance callable hook for waveform acquisition.

        The hook takes precedence over the deprecated global sample fallback.
        Passing None clears the hook and restores fallback behavior.

        Args:
            hook: Callable returning waveform data ((voltages, times), dict, or DataFrame), or None.

        Raises:
            TypeError: If hook is not callable and not None.
        """
        if hook is not None and not callable(hook):
            raise TypeError(f"waveform_hook must be callable or None, got {type(hook).__name__}")
        self._waveform_hook = hook

    def set_channel_hook(self, hook: Optional[Callable[..., Any]]) -> None:
        """Alias for set_waveform_hook."""
        self.set_waveform_hook(hook)

    def set_data_hook(self, hook: Optional[Callable[..., Any]]) -> None:
        """Alias for set_waveform_hook."""
        self.set_waveform_hook(hook)

    @property
    def sample(self) -> Any:
        """Return instance-specific or shared ferroelectric sample fallback."""
        if hasattr(self, "_instance_sample"):
            return self._instance_sample
        return super().sample

    @sample.setter
    def sample(self, sample: Any) -> None:
        self._instance_sample = sample

    @sample.deleter
    def sample(self) -> None:
        if hasattr(self, "_instance_sample"):
            del self._instance_sample

    def idn(self) -> str:
        """
        Get the identification string of the virtual oscilloscope.

        Returns:
            str: Identification string for the virtual oscilloscope.
        """
        return "Virtual Oscilloscope"

    def write(self, command: str) -> None:
        """Accept SCPI-like write commands."""
        cmd = str(command).upper().strip()
        if cmd == "*RST":
            self.reset()
        elif cmd == "*CLS":
            self.clear()
        return None

    def query(self, command: str) -> str:
        """Respond to common SCPI queries used by base helpers."""
        cmd = str(command).upper().strip()
        if cmd == "*IDN?":
            return self.idn()
        if cmd == "*ESR?":
            return "0"
        if cmd == "*OPC?":
            return "1"
        return ""

    def reset(self) -> None:
        """
        Reset the virtual scope configuration to factory defaults.

        Restores default scales, triggers, and channel states while preserving
        the injected hook intact.

        Driver reset does NOT reset setup-owned state: closures, external material
        models, timebase clocks, and RNG seeds are owned by the test fixture or
        VirtualBench and must be reset there.
        """
        self.state = {
            "channels_on": {ch: True for ch in self.channel},
            "vdiv": {ch: 1.0 for ch in self.channel},
            "y_range": {ch: 8.0 for ch in self.channel},
            "y_position": {ch: 0.0 for ch in self.channel},
            "input_coupling": {ch: "DC" for ch in self.channel},
            "probe_attenuation": {ch: 1.0 for ch in self.channel},
            "tdiv": 1e-3,
            "x_range": 8e-3,
            "x_position": 0.0,
            "trigger_source": "CHAN1",
            "trigger_level": 0.0,
            "trigger_slope": "POS",
            "trigger_mode": "EDGE",
            "trigger_sweep": "AUTO",
            "acquisition_mode": "NORM",
            "acquisition_channel": 1,
            "running": False,
            "armed": False,
        }
        self._requested_acquisition_points = None

    def clear(self) -> None:
        """Clear status (safe no-op in virtual mode)."""
        return None

    def initialize(self) -> None:
        """Initialize virtual scope to a known state without external I/O."""
        self.autoscale()
        self.clear()

    def autoscale(self) -> None:
        """Reset oscilloscope scales to factory defaults."""
        self.reset()

    def get_state(self) -> dict[str, Any]:
        """Return a detached copy of the current virtual oscilloscope state."""
        return {
            k: v.copy() if isinstance(v, dict) else v
            for k, v in self.state.items()
        }

    def toggle_channel(self, channel: int, on: bool = True) -> None:
        """
        Enable or disable a specific channel.

        Args:
            channel: Channel number (1-4).
            on: True to enable, False to disable.
        """
        if isinstance(channel, bool) or not isinstance(channel, Real):
            raise TypeError("channel must be an integer")
        ch = int(channel)
        if ch not in self.channel:
            raise ValueError(f"Invalid channel {channel}. Must be one of {self.channel}")
        if not isinstance(on, (bool, int)) or on not in (False, True, 0, 1):
            raise TypeError("on must be a boolean or 0/1")
        self.state["channels_on"][ch] = bool(on)

    def set_vertical_scale(
        self,
        channel: int,
        vdiv: Optional[float] = None,
        y_range: Optional[float] = None,
    ) -> None:
        """
        Set the vertical scale parameters for a channel.

        Args:
            channel: Channel number (1-4).
            vdiv: Volts per division setting (> 0).
            y_range: Total vertical range in volts (> 0).
        """
        if isinstance(channel, bool) or not isinstance(channel, Real):
            raise TypeError("channel must be an integer")
        ch = int(channel)
        if ch not in self.channel:
            raise ValueError(f"Invalid channel {channel}. Must be one of {self.channel}")

        if vdiv is None and y_range is None:
            raise ValueError("Either vdiv or y_range must be provided")

        v_f: Optional[float] = None
        if vdiv is not None:
            if isinstance(vdiv, bool) or not isinstance(vdiv, Real):
                raise TypeError("vdiv must be a positive finite number")
            v_f = float(vdiv)
            if not math.isfinite(v_f) or v_f <= 0:
                raise ValueError(f"vdiv must be a positive finite number, got {vdiv!r}")

        y_f: Optional[float] = None
        if y_range is not None:
            if isinstance(y_range, bool) or not isinstance(y_range, Real):
                raise TypeError("y_range must be a positive finite number")
            y_f = float(y_range)
            if not math.isfinite(y_f) or y_f <= 0:
                raise ValueError(f"y_range must be a positive finite number, got {y_range!r}")

        if v_f is not None and y_f is None:
            self.state["vdiv"][ch] = v_f
            self.state["y_range"][ch] = v_f * 8.0
        elif y_f is not None and v_f is None:
            self.state["y_range"][ch] = y_f
            self.state["vdiv"][ch] = y_f / 8.0
        else:
            self.state["vdiv"][ch] = v_f
            self.state["y_range"][ch] = y_f

    def set_vertical_position(self, channel: int, y_position: float) -> None:
        """
        Set the vertical position of a channel in divisions.

        Args:
            channel: Channel number (1-4).
            y_position: Vertical position in divisions (-40.0 to 40.0).
        """
        if isinstance(channel, bool) or not isinstance(channel, Real):
            raise TypeError("channel must be an integer")
        ch = int(channel)
        if ch not in self.channel:
            raise ValueError(f"Invalid channel {channel}. Must be one of {self.channel}")
        if isinstance(y_position, bool) or not isinstance(y_position, Real):
            raise TypeError("y_position must be numeric")
        y_f = float(y_position)
        if not math.isfinite(y_f):
            raise ValueError("y_position must be finite")
        if not self.y_position[0] <= y_f <= self.y_position[1]:
            raise ValueError(f"y_position {y_f} is outside range {self.y_position}")
        self.state["y_position"][ch] = y_f

    def set_input_coupling(self, channel: int, input_coupling: str) -> None:
        """
        Set the input coupling mode for a channel.

        Args:
            channel: Channel number (1-4).
            input_coupling: Coupling mode ("AC" or "DC").
        """
        if isinstance(channel, bool) or not isinstance(channel, Real):
            raise TypeError("channel must be an integer")
        ch = int(channel)
        if ch not in self.channel:
            raise ValueError(f"Invalid channel {channel}. Must be one of {self.channel}")
        c_str = str(input_coupling).upper().strip()
        if c_str not in self.input_coupling:
            raise ValueError(f"input_coupling must be one of {self.input_coupling}, got {input_coupling!r}")
        self.state["input_coupling"][ch] = c_str

    def set_probe_attenuation(self, channel: int, probe_attenuation: float) -> None:
        """
        Set the probe attenuation factor for a channel.

        Args:
            channel: Channel number (1-4).
            probe_attenuation: Attenuation factor (0.001 to 10000.0).
        """
        if isinstance(channel, bool) or not isinstance(channel, Real):
            raise TypeError("channel must be an integer")
        ch = int(channel)
        if ch not in self.channel:
            raise ValueError(f"Invalid channel {channel}. Must be one of {self.channel}")
        if isinstance(probe_attenuation, bool) or not isinstance(probe_attenuation, Real):
            raise TypeError("probe_attenuation must be numeric")
        att_f = float(probe_attenuation)
        if not math.isfinite(att_f) or att_f <= 0:
            raise ValueError("probe_attenuation must be a positive finite number")
        if not self.probe_attenuation[0] <= att_f <= self.probe_attenuation[1]:
            raise ValueError(f"probe_attenuation {att_f} is outside range {self.probe_attenuation}")
        self.state["probe_attenuation"][ch] = att_f

    def set_horizontal_scale(
        self,
        tdiv: Optional[float] = None,
        x_range: Optional[float] = None,
    ) -> None:
        """
        Set horizontal timebase scale parameters.

        Args:
            tdiv: Time per division in seconds (> 0).
            x_range: Total horizontal range in seconds (> 0).
        """
        if tdiv is None and x_range is None:
            raise ValueError("Either tdiv or x_range must be provided")

        t_f: Optional[float] = None
        if tdiv is not None:
            if isinstance(tdiv, bool) or not isinstance(tdiv, Real):
                raise TypeError("tdiv must be a positive finite number")
            t_f = float(tdiv)
            if not math.isfinite(t_f) or t_f <= 0:
                raise ValueError(f"tdiv must be a positive finite number, got {tdiv!r}")

        x_f: Optional[float] = None
        if x_range is not None:
            if isinstance(x_range, bool) or not isinstance(x_range, Real):
                raise TypeError("x_range must be a positive finite number")
            x_f = float(x_range)
            if not math.isfinite(x_f) or x_f <= 0:
                raise ValueError(f"x_range must be a positive finite number, got {x_range!r}")

        if t_f is not None and x_f is None:
            self.state["tdiv"] = t_f
            self.state["x_range"] = t_f * 8.0
        elif x_f is not None and t_f is None:
            self.state["x_range"] = x_f
            self.state["tdiv"] = x_f / 8.0
        else:
            self.state["tdiv"] = t_f
            self.state["x_range"] = x_f

    def set_horizontal_position(self, x_position: float) -> None:
        """
        Set the horizontal position of the trigger point.

        Args:
            x_position: Horizontal position in seconds (-500.0 to 500.0).
        """
        if isinstance(x_position, bool) or not isinstance(x_position, Real):
            raise TypeError("x_position must be numeric")
        pos_f = float(x_position)
        if not math.isfinite(pos_f):
            raise ValueError("x_position must be finite")
        if not self.x_position[0] <= pos_f <= self.x_position[1]:
            raise ValueError(f"x_position {pos_f} is outside range {self.x_position}")
        self.state["x_position"] = pos_f

    def configure_horizontal(
        self,
        tdiv: Optional[float] = None,
        x_range: Optional[float] = None,
        x_position: Optional[float] = None,
    ) -> None:
        """Configure multiple horizontal parameters at once."""
        if tdiv is not None or x_range is not None:
            self.set_horizontal_scale(tdiv, x_range)
        if x_position is not None:
            self.set_horizontal_position(x_position)

    def set_trigger_source(self, trigger_source: Union[int, str]) -> None:
        """
        Set the trigger source channel.

        Args:
            trigger_source: Channel number (1-4) or string identifier ('CHAN1', 'EXT', etc.).
        """
        mapping = {
            1: "CHAN1", 2: "CHAN2", 3: "CHAN3", 4: "CHAN4",
            "1": "CHAN1", "2": "CHAN2", "3": "CHAN3", "4": "CHAN4",
        }
        src = mapping.get(trigger_source, str(trigger_source).upper())
        valid_sources = ["CHAN1", "CHAN2", "CHAN3", "CHAN4", "EXT", "LINE", "WGEN"]
        if src not in valid_sources:
            raise ValueError(f"trigger_source must be one of {valid_sources}, got {trigger_source!r}")
        self.state["trigger_source"] = src

    def set_trigger_level(self, trigger_level: float) -> None:
        """
        Set the trigger voltage level.

        Args:
            trigger_level: Voltage level to trigger at (-6.0V to 6.0V).
        """
        if isinstance(trigger_level, bool) or not isinstance(trigger_level, Real):
            raise TypeError("trigger_level must be numeric")
        lvl_f = float(trigger_level)
        if not math.isfinite(lvl_f):
            raise ValueError("trigger_level must be finite")
        if not self.trigger_level[0] <= lvl_f <= self.trigger_level[1]:
            raise ValueError(f"trigger_level {lvl_f} is outside range {self.trigger_level}")
        self.state["trigger_level"] = lvl_f

    def set_trigger_slope(self, trigger_slope: str) -> None:
        """
        Set the trigger slope mode.

        Args:
            trigger_slope: Edge slope ("POS", "NEG", "EITH", "ALT").
        """
        slope_str = str(trigger_slope).upper()
        if slope_str not in self.trigger_slope:
            raise ValueError(f"trigger_slope must be one of {self.trigger_slope}, got {trigger_slope!r}")
        self.state["trigger_slope"] = slope_str

    def set_trigger_mode(self, trigger_mode: str) -> None:
        """
        Set the trigger mode.

        Args:
            trigger_mode: Trigger mode ("EDGE").
        """
        mode_str = str(trigger_mode).upper()
        if mode_str not in self.trigger_mode:
            raise ValueError(f"trigger_mode must be one of {self.trigger_mode}, got {trigger_mode!r}")
        self.state["trigger_mode"] = mode_str

    def set_trigger_sweep(self, trigger_sweep: str) -> None:
        """
        Set the trigger sweep mode.

        Args:
            trigger_sweep: Trigger sweep mode ("AUTO" or "NORM").
        """
        swp_str = str(trigger_sweep).upper()
        if swp_str not in self.trigger_sweep:
            raise ValueError(f"trigger_sweep must be one of {self.trigger_sweep}, got {trigger_sweep!r}")
        self.state["trigger_sweep"] = swp_str

    def configure_trigger(
        self,
        trigger_source: Optional[Union[int, str]] = None,
        trigger_level: Optional[float] = None,
        trigger_slope: Optional[str] = None,
        trigger_mode: Optional[str] = None,
    ) -> None:
        """Configure multiple trigger parameters at once."""
        if trigger_source is not None:
            self.set_trigger_source(trigger_source)
        if trigger_level is not None:
            self.set_trigger_level(trigger_level)
        if trigger_slope is not None:
            self.set_trigger_slope(trigger_slope)
        if trigger_mode is not None:
            self.set_trigger_mode(trigger_mode)

    def manual_trigger(self) -> None:
        """Sends a manual force trigger event to the oscilloscope."""
        return None

    def arm(self) -> None:
        """Arms the oscilloscope trigger system."""
        self.state["armed"] = True

    def set_acquisition(self) -> None:
        """Configure basic acquisition parameters (safe no-op)."""
        return None

    def set_acquisition_channel(self, channel: int) -> None:
        """
        Set the active acquisition channel.

        Args:
            channel: Channel number (1-4).
        """
        if isinstance(channel, bool) or not isinstance(channel, Real):
            raise TypeError("channel must be an integer")
        ch = int(channel)
        if ch not in self.channel:
            raise ValueError(f"Invalid channel {channel}. Must be one of {self.channel}")
        self.state["acquisition_channel"] = ch

    def set_acquisition_mode(self, acquisition_mode: str) -> None:
        """
        Set the acquisition mode.

        Args:
            acquisition_mode: One of ["NORM", "AVER", "HRES", "PEAK"].
        """
        acq_str = str(acquisition_mode).upper()
        if acq_str not in self.acquisition_mode:
            raise ValueError(f"acquisition_mode must be one of {self.acquisition_mode}, got {acquisition_mode!r}")
        self.state["acquisition_mode"] = acq_str

    def set_acquisition_points(self, acquisition_points: int) -> None:
        """Set the requested acquisition size, bounded by simulation capacity."""
        if isinstance(acquisition_points, bool) or not isinstance(acquisition_points, Real):
            raise TypeError("acquisition_points must be an integer")
        pts_f = float(acquisition_points)
        if not math.isfinite(pts_f) or not pts_f.is_integer() or pts_f < 2:
            raise ValueError(f"acquisition_points must be an integer >= 2, got {acquisition_points!r}")
        self._requested_acquisition_points = int(pts_f)

    def configure_acquisition(
        self,
        channel: Optional[int] = None,
        acquisition_mode: Optional[str] = None,
        acquisition_points: Optional[int] = None,
    ) -> None:
        """Configure multiple acquisition parameters at once."""
        if channel is not None:
            self.set_acquisition_channel(channel)
        if acquisition_mode is not None:
            self.set_acquisition_mode(acquisition_mode)
        if acquisition_points is not None:
            self.set_acquisition_points(acquisition_points)

    def toggle_acquisition(self, run: bool = True) -> None:
        """
        Start or stop the acquisition.

        Args:
            run: True to start acquisition, False to stop.
        """
        if not isinstance(run, (bool, int)) or run not in (False, True, 0, 1):
            raise TypeError("run must be a boolean or 0/1")
        self.state["running"] = bool(run)

    def quick_read(self) -> np.ndarray:
        """
        Generate a synthetic waveform for testing.

        Returns:
            numpy.ndarray: Synthetic waveform data as 8-bit unsigned integers.
        """
        requested_points = self._requested_acquisition_points
        points = self._simulation_points if requested_points is None else min(
            requested_points,
            self._simulation_points,
        )
        warn_for_large_simulation_points(points, label="virtual oscilloscope waveform")
        t = np.linspace(0, self.state["x_range"], points)
        freq = 1.0 / (self.state["x_range"] if self.state["x_range"] else 1e-3)
        v = np.sin(2 * np.pi * freq * t) * self.state["vdiv"][self.state["acquisition_channel"]] * 2
        return v.astype(np.uint8)

    def get_data(self, channel: Optional[int] = None) -> pd.DataFrame:
        """
        Get voltage and time waveform data from the virtual oscilloscope.

        If a per-instance `waveform_hook` is injected, calls the hook directly
        without accessing the deprecated shared sample fallback. Otherwise,
        falls back to `self.sample.get_voltage_response()`.

        Args:
            channel: Optional channel number (1-4). Defaults to current acquisition channel.

        Returns:
            pandas.DataFrame: DataFrame containing 'Time' (seconds) and 'Voltage' (volts) columns.

        Raises:
            ValueError: If channel is invalid or hook returns invalid data.
            TypeError: If hook returns an unsupported type.
        """
        if channel is not None:
            if isinstance(channel, bool) or not isinstance(channel, Real):
                raise TypeError("channel must be an integer")
            ch = int(channel)
            if ch not in self.channel:
                raise ValueError(f"Invalid channel {channel}. Must be one of {self.channel}")
        else:
            ch = int(self.state["acquisition_channel"])

        if self._waveform_hook is not None:
            raw = self._invoke_hook(self._waveform_hook, ch)
            return self._normalize_waveform_response(raw)

        # Deprecated fallback to shared ferroelectric sample
        if hasattr(self, "sample") and self.sample is not None:
            voltages, times = self.sample.get_voltage_response()
            return pd.DataFrame({"Time": times, "Voltage": voltages})

        raise RuntimeError("VirtualScope has no injected waveform_hook and no shared sample fallback")

    def _invoke_hook(self, hook: Callable[..., Any], channel: int) -> Any:
        """Bind hook parameters before invoking once; propagate hook exceptions unchanged."""
        try:
            sig = inspect.signature(hook)
        except (ValueError, TypeError):
            return hook(channel)

        pts = (
            self._simulation_points
            if self._requested_acquisition_points is None
            else min(self._requested_acquisition_points, self._simulation_points)
        )

        values: dict[str, Any] = {
            "channel": channel,
            "ch": channel,
            "vdiv": self.state["vdiv"][channel],
            "y_range": self.state["y_range"][channel],
            "y_position": self.state["y_position"][channel],
            "tdiv": self.state["tdiv"],
            "x_range": self.state["x_range"],
            "x_position": self.state["x_position"],
            "coupling": self.state["input_coupling"][channel],
            "probe_attenuation": self.state["probe_attenuation"][channel],
            "points": pts,
            "state": self.get_state(),
        }

        params = list(sig.parameters.values())
        args: list[Any] = []
        kwargs: dict[str, Any] = {}

        # 1. Positional-only parameters
        positional = [p for p in params if p.kind == inspect.Parameter.POSITIONAL_ONLY]
        if positional:
            for i, p in enumerate(positional):
                if p.name in values:
                    args.append(values[p.name])
                elif p.default is not inspect.Parameter.empty:
                    args.append(p.default)
                elif i == 0:
                    args.append(channel)
                elif i == 1:
                    args.append(self.state["tdiv"])
                elif i == 2:
                    args.append(self.state["vdiv"][channel])
                else:
                    raise TypeError(f"waveform_hook has unsupported required positional parameter {p.name!r}")

        # 2. Positional or keyword parameters
        for i, p in enumerate(params):
            if p.kind == inspect.Parameter.POSITIONAL_OR_KEYWORD:
                if p.name in values:
                    kwargs[p.name] = values[p.name]
                elif p.default is not inspect.Parameter.empty:
                    continue
                elif not positional and i == 0:
                    kwargs[p.name] = channel
                elif not positional and i == 1:
                    kwargs[p.name] = self.state["tdiv"]
                elif not positional and i == 2:
                    kwargs[p.name] = self.state["vdiv"][channel]
            elif p.kind == inspect.Parameter.KEYWORD_ONLY and p.name in values:
                kwargs[p.name] = values[p.name]

        # 3. Variadic *args and **kwargs
        if any(p.kind == inspect.Parameter.VAR_POSITIONAL for p in params) and not args and not kwargs:
            args.append(channel)
        if any(p.kind == inspect.Parameter.VAR_KEYWORD for p in params):
            kwargs.update({k: v for k, v in values.items() if k not in sig.parameters})

        try:
            sig.bind(*args, **kwargs)
        except TypeError as error:
            if len(params) == 0:
                return hook()
            raise TypeError("waveform_hook has incompatible signature") from error

        return hook(*args, **kwargs)

    @staticmethod
    def _normalize_waveform_response(raw: Any) -> pd.DataFrame:
        """Normalize raw hook output into standard pd.DataFrame with 'Time' and 'Voltage' columns."""
        if isinstance(raw, pd.DataFrame):
            cols_lower = {str(c).strip().lower(): c for c in raw.columns}
            time_col: Optional[Any] = None
            for candidate in ("time", "t", "timestamp"):
                if candidate in cols_lower:
                    time_col = cols_lower[candidate]
                    break
            volt_col: Optional[Any] = None
            for candidate in ("voltage", "v", "volt", "ch1", "chan1", "channel1"):
                if candidate in cols_lower and cols_lower[candidate] != time_col:
                    volt_col = cols_lower[candidate]
                    break

            if time_col is None or volt_col is None:
                if len(raw.columns) == 2:
                    col0, col1 = raw.columns[0], raw.columns[1]
                    if time_col is not None:
                        volt_col = col1 if time_col == col0 else col0
                    else:
                        time_col, volt_col = col0, col1
                else:
                    raise ValueError(
                        f"DataFrame returned by waveform_hook must contain time and voltage columns, got {list(raw.columns)}"
                    )

            try:
                t_arr = np.asarray(raw[time_col], dtype=np.float64)
                v_arr = np.asarray(raw[volt_col], dtype=np.float64)
            except (ValueError, TypeError) as exc:
                raise TypeError(f"Failed to convert waveform data to float64 arrays: {exc}") from exc

            if len(t_arr) == 0:
                raise ValueError("waveform data must not be empty")
            if not np.all(np.isfinite(t_arr)) or np.any(t_arr < 0):
                raise ValueError("time values must be finite and non-negative")

            return pd.DataFrame({"Time": t_arr, "Voltage": v_arr})

        if isinstance(raw, Mapping) or (hasattr(raw, "keys") and callable(raw.keys)):
            keys_lower = {str(k).strip().lower(): k for k in raw.keys()}
            time_key: Optional[Any] = None
            for candidate in ("time", "t", "timestamp"):
                if candidate in keys_lower:
                    time_key = keys_lower[candidate]
                    break
            volt_key: Optional[Any] = None
            for candidate in ("voltage", "v", "volt", "ch1", "chan1", "channel1"):
                if candidate in keys_lower and keys_lower[candidate] != time_key:
                    volt_key = keys_lower[candidate]
                    break

            if time_key is None or volt_key is None:
                if len(raw) == 2:
                    k0, k1 = list(raw.keys())[:2]
                    if time_key is not None:
                        volt_key = k1 if time_key == k0 else k0
                    else:
                        time_key, volt_key = k0, k1
                else:
                    raise ValueError(
                        f"Mapping returned by waveform_hook must contain time and voltage keys, got {list(raw.keys())}"
                    )

            try:
                t_arr = np.asarray(raw[time_key], dtype=np.float64)
                v_arr = np.asarray(raw[volt_key], dtype=np.float64)
            except (ValueError, TypeError) as exc:
                raise TypeError(f"Failed to convert waveform data to float64 arrays: {exc}") from exc

            if len(t_arr) == 0:
                raise ValueError("waveform data must not be empty")
            if len(t_arr) != len(v_arr):
                raise ValueError(f"time and voltage arrays must have matching length: {len(t_arr)} != {len(v_arr)}")
            if not np.all(np.isfinite(t_arr)) or np.any(t_arr < 0):
                raise ValueError("time values must be finite and non-negative")

            return pd.DataFrame({"Time": t_arr, "Voltage": v_arr})

        if isinstance(raw, (tuple, list)) and len(raw) == 2:
            try:
                voltages = np.asarray(raw[0], dtype=np.float64)
                times = np.asarray(raw[1], dtype=np.float64)
            except (ValueError, TypeError) as exc:
                raise TypeError(f"Failed to convert waveform tuple elements to float64 arrays: {exc}") from exc

            if len(voltages) == 0:
                raise ValueError("waveform data arrays must not be empty")
            if len(voltages) != len(times):
                raise ValueError(f"waveform data arrays must have matching length, got {len(voltages)} and {len(times)}")

            if not np.all(np.isfinite(times)) or np.any(times < 0):
                raise ValueError("time array must be finite and non-negative")

            return pd.DataFrame({"Time": times, "Voltage": voltages})

        raise TypeError(
            f"waveform_hook must return a 2-tuple (voltages, times), dict, or DataFrame, got {type(raw).__name__}"
        )
