"""
Mixin class for instruments that communicate via the SCPI-99 / IEEE 488.2 protocol.
"""


class Scpi():
    """
    All SCPI instruments must allow for all base SCPI commands to work!
    This is taken from the SCPI-99 standard and includes the IEEE 488.2 Mandated Commands.
    https://www.ivifoundation.org/downloads/SCPI/scpi-99.pdf
    """

    def __init__(self, address, **kwargs):
        """
        Opens the instrument and enables communication with it.

        In the case of SCPI, this is usually done over GPIB, USB, or Ethernet.
        The address is a VISA resource string that represents the connection
        method and address of the instrument
        (e.g. ``'GPIB::1::INSTR'``, ``'USB0::0x1234::0x5678::INSTR'``).
        Uses the built-in PiecManager to handle the connection and
        communication with the instrument.
        """
        super().__init__(address, **kwargs)

    def idn(self):
        """
        Queries the instrument identification string via ``*IDN?``.

        By default this returns the raw string; subclasses may override
        to format it for better readability.

        Returns:
            str: Instrument identification string.
        """
        raw_idn_string = self.instrument.query("*IDN?")
        return raw_idn_string

    def reset(self):
        """
        Resets the instrument to its default state via ``*RST`` with the
        trigger sweep left in **AUTO** mode.

        After reset the instrument should be free-running and acquiring fresh
        data so that any previously displayed waveforms are cleared.  Also
        re-initialises the internal state tracker.

        Subclasses should override this method if the instrument's ``*RST``
        behavior differs (e.g., LeCroy scopes stop the trigger on ``*RST``
        and need an explicit command to restore AUTO sweep).
        """
        #SCPI Command
        self.instrument.write("*RST")
        #set _current_attribute to None
        self._initialize_state()

    def clear(self):
        """
        Clears the instrument's status registers and error queue via ``*CLS``.

        Useful for clearing any errors or status messages that may have been
        generated by previous operations.
        """
        self.instrument.write("*CLS")

    def error(self):
        """
        Queries the instrument's Standard Event Status Register via ``*ESR?``.

        Useful for checking if there are any errors that need to be addressed.
        For specific error messages, subclasses may alternatively query
        ``SYST:ERR?``.

        Returns:
            str: The event status register value.
        """
        return self.instrument.query("*ESR?")

    def wait(self):
        """
        Sends the ``*WAI`` command to wait for all pending operations to complete.

        Useful for ensuring that the instrument is ready before sending any
        further commands.
        """
        self.instrument.write("*WAI")

    def self_test(self):
        """
        Runs the instrument's built-in self-test via ``*TST?``.

        Temporarily increases the VISA timeout since self-tests can take
        30+ seconds.

        Returns:
            str: Self-test result (typically ``'0'`` for pass).
        """
        original_timeout = self.instrument.timeout
        self.instrument.timeout = 60000  # 60 seconds
        try:
            return self.instrument.query("*TST?")
        finally:
            self.instrument.timeout = original_timeout

    def operation_complete(self):
        """
        Queries whether the last operation has finished via ``*OPC?``.

        Useful for ensuring that the instrument is ready before sending any
        further commands.

        Returns:
            str: ``'1'`` when the operation is complete.
        """
        return self.instrument.query("*OPC?")
    
    # --- Utility Commands ---

    def initialize(self):
        """
        Convenience method that resets and clears the instrument to bring it
        to a known good starting state.

        Calls :meth:`reset` followed by :meth:`clear`.
        """
        self.reset()
        self.clear()